imports:
    - { resource: "grids/*" }

knp_gaufrette:
    adapters:
        odiseo_blog_image:
            local:
                directory: "%kernel.project_dir%/public/media/image"
                create: true
    filesystems:
        odiseo_blog_image:
            adapter: odiseo_blog_image
